const $ = <T extends HTMLElement>(selector: string) => document.querySelector(selector) as T;

export type DomElements = {
  viewport: HTMLCanvasElement;
  overlayCanvas: HTMLCanvasElement;
  viewportShell: HTMLElement;
  loading: HTMLElement;
  loadingLabel: HTMLElement;
  modelDrop: HTMLButtonElement;
  modelInput: HTMLInputElement;
  animationDrop: HTMLButtonElement;
  animationDropHint: HTMLElement;
  animationDropHintClose: HTMLButtonElement;
  animationInput: HTMLInputElement;
  assetList: HTMLElement;
  modelName: HTMLElement;
  modelStatus: HTMLElement;
  bonesReadout: HTMLButtonElement;
  bonesReadoutValue: HTMLElement;
  bonesPopover: HTMLElement;
  bonesPopoverList: HTMLElement;
  queueCount: HTMLElement;
  dataDuration: HTMLElement;
  dataKeyframes: HTMLElement;
  dataFormat: HTMLElement;
  bakeOperationRow: HTMLElement;
  bakeFps: HTMLSelectElement;
  bakeFrameStep: HTMLSelectElement;
  bakeFrameMidLabel: HTMLElement;
  bakeFrameMaxLabel: HTMLElement;
  bakeApply: HTMLButtonElement;
  bakeCancel: HTMLButtonElement;
  bakeRevert: HTMLButtonElement;
  download: HTMLButtonElement;
  downloadName: HTMLElement;
  downloadSize: HTMLElement;
  speedOperationRow: HTMLElement;
  speedMultiplier: HTMLInputElement;
  speedMultiplierValue: HTMLElement;
  play: HTMLButtonElement;
  playIcon: HTMLElement;
  loopToggle: HTMLButtonElement;
  currentFrame: HTMLElement;
  totalFrames: HTMLElement;
  currentTime: HTMLElement;
  previousFrame: HTMLButtonElement;
  nextFrame: HTMLButtonElement;
  viewportBackgroundButton: HTMLButtonElement;
  bonesToggleButton: HTMLButtonElement;
  resetView: HTMLButtonElement;
  viewportZoomOutButton: HTMLButtonElement;
  viewportZoomButton: HTMLButtonElement;
  viewportZoomRange: HTMLInputElement;
  timelineRuler: HTMLElement;
  timelineRulerSticky: HTMLElement;
  timelineBody: HTMLElement;
  timelineScroll: HTMLElement;
  timelineScrollContent: HTMLElement;
  trackLanes: HTMLElement;
  transformsToggle: HTMLButtonElement;
  transformBoneLabels: HTMLElement;
  transformBoneLanes: HTMLElement;
  transformsKeys: HTMLElement;
  faceKeys: HTMLElement;
  playhead: HTMLElement;
  zoomIn: HTMLButtonElement;
  zoomOut: HTMLButtonElement;
  toast: HTMLElement;
  toastMessage: HTMLElement;
  fbxRigDialog: HTMLDialogElement;
  fbxRigFileName: HTMLElement;
};

export const dom: DomElements = {
  viewport: $<HTMLCanvasElement>('#viewport'),
  overlayCanvas: $<HTMLCanvasElement>('#overlay-canvas'),
  viewportShell: $<HTMLElement>('#viewport-shell'),
  loading: $<HTMLElement>('#loading-overlay'),
  loadingLabel: $<HTMLElement>('#loading-label'),
  modelDrop: $<HTMLButtonElement>('#model-drop'),
  modelInput: $<HTMLInputElement>('#vrm-file-input'),
  animationDrop: $<HTMLButtonElement>('#animation-drop'),
  animationDropHint: $<HTMLElement>('#animation-drop-hint'),
  animationDropHintClose: $<HTMLButtonElement>('#animation-drop-hint-close'),
  animationInput: $<HTMLInputElement>('#animation-file-input'),
  assetList: $<HTMLElement>('#asset-list'),
  modelName: $<HTMLElement>('#model-name'),
  modelStatus: $<HTMLElement>('#model-status'),
  bonesReadout: $<HTMLButtonElement>('#readout-bones'),
  bonesReadoutValue: $<HTMLElement>('#readout-bones-value'),
  bonesPopover: $<HTMLElement>('#bones-popover'),
  bonesPopoverList: $<HTMLElement>('#bones-popover-list'),
  queueCount: $<HTMLElement>('#queue-count'),
  dataDuration: $<HTMLElement>('#data-duration'),
  dataKeyframes: $<HTMLElement>('#data-keyframes'),
  dataFormat: $<HTMLElement>('#data-format'),
  bakeOperationRow: $<HTMLElement>('#bake-operation-row'),
  bakeFps: $<HTMLSelectElement>('#bake-fps'),
  bakeFrameStep: $<HTMLSelectElement>('#bake-frame-step'),
  bakeFrameMidLabel: $<HTMLElement>('#bake-frame-mid-label'),
  bakeFrameMaxLabel: $<HTMLElement>('#bake-frame-max-label'),
  bakeApply: $<HTMLButtonElement>('#bake-apply-button'),
  bakeCancel: $<HTMLButtonElement>('#bake-cancel-button'),
  bakeRevert: $<HTMLButtonElement>('#bake-revert-button'),
  download: $<HTMLButtonElement>('#download-button'),
  downloadName: $<HTMLElement>('#download-name'),
  downloadSize: $<HTMLElement>('#download-size'),
  speedOperationRow: $<HTMLElement>('#speed-operation-row'),
  speedMultiplier: $<HTMLInputElement>('#speed-multiplier'),
  speedMultiplierValue: $<HTMLElement>('#speed-multiplier-value'),
  play: $<HTMLButtonElement>('#play-button'),
  playIcon: $<HTMLElement>('#play-icon'),
  loopToggle: $<HTMLButtonElement>('#loop-toggle'),
  currentFrame: $<HTMLElement>('#current-frame'),
  totalFrames: $<HTMLElement>('#total-frames'),
  currentTime: $<HTMLElement>('#current-time'),
  previousFrame: $<HTMLButtonElement>('#previous-frame-button'),
  nextFrame: $<HTMLButtonElement>('#next-frame-button'),
  viewportBackgroundButton: $<HTMLButtonElement>('#viewport-background-button'),
  bonesToggleButton: $<HTMLButtonElement>('#bones-toggle-button'),
  resetView: $<HTMLButtonElement>('#reset-view-button'),
  viewportZoomOutButton: $<HTMLButtonElement>('#viewport-zoom-out-button'),
  viewportZoomButton: $<HTMLButtonElement>('#viewport-zoom-button'),
  viewportZoomRange: $<HTMLInputElement>('#viewport-zoom-range'),
  timelineRuler: $<HTMLElement>('#timeline-ruler'),
  timelineRulerSticky: $<HTMLElement>('#timeline-ruler-sticky'),
  timelineBody: $<HTMLElement>('#timeline-body'),
  timelineScroll: $<HTMLElement>('#timeline-scroll'),
  timelineScrollContent: $<HTMLElement>('#timeline-scroll-content'),
  trackLanes: $<HTMLElement>('#track-lanes'),
  transformsToggle: $<HTMLButtonElement>('#transforms-toggle'),
  transformBoneLabels: $<HTMLElement>('#transform-bone-labels'),
  transformBoneLanes: $<HTMLElement>('#transform-bone-lanes'),
  transformsKeys: $<HTMLElement>('#transforms-keys'),
  faceKeys: $<HTMLElement>('#face-keys'),
  playhead: $<HTMLElement>('#playhead'),
  zoomIn: $<HTMLButtonElement>('#zoom-in-button'),
  zoomOut: $<HTMLButtonElement>('#zoom-out-button'),
  toast: $<HTMLElement>('#toast'),
  toastMessage: $<HTMLElement>('#toast-message'),
  fbxRigDialog: $<HTMLDialogElement>('#fbx-rig-dialog'),
  fbxRigFileName: $<HTMLElement>('#fbx-rig-file-name'),
};
